#!/usr/bin/env python3
"""qfuzz finding nan-quantizelinear-dequantizelinear-4686bf: nan-inf in QuantizeLinear -> DequantizeLinear (levels: all, disable, extended)

Standalone reproducer -- requires only numpy, onnx and onnxruntime.
Generated by qfuzz (https://github.com/ -- see qfuzz/README.md) from seed 7
(pattern `quantize`), then delta-debugged.

Verdict class : nan-inf
Failing levels: all, disable, extended   (ORT graph optimization levels; 'disable' = ORT_DISABLE_ALL)
Graph         : QuantizeLinear -> DequantizeLinear

EXPECTED holds the exact ONNX-spec result computed by qfuzz's reference
interpreter (exact integer / rational arithmetic, round-half-to-even,
saturation) and SLACK the per-element deviation a conforming float32
implementation is allowed (0 = must be bit-exact).

Run:  python repro.py        -> prints a JSON line, exit code 0 always.
      python repro.py --check -> exit code 1 if the discrepancy reproduces.
"""
import json
import sys

import numpy as np
import onnx
import onnxruntime as ort
from onnx import TensorProto, helper, numpy_helper

CASE = json.loads(r"""{"opset": 21, "nodes": [{"op": "QuantizeLinear", "inputs": ["x1", "c2", "c3"], "outputs": ["t4"], "attrs": {"saturate": 0}, "domain": ""}, {"op": "DequantizeLinear", "inputs": ["t4", "obs_s5", "obs_z6"], "outputs": ["t7"], "attrs": {}, "domain": ""}], "inputs": [{"name": "x1", "dtype": "float32", "shape": [1, 1, 1, 1], "data": [-0.03999999910593033], "dims": ["d0", "d1", "d2", "d3"]}], "inits": [{"name": "c2", "dtype": "float32", "shape": [], "data": [8.199999865610152e-05], "dims": []}, {"name": "c3", "dtype": "float8e4m3fn", "shape": [], "data": [0], "dims": []}, {"name": "obs_s5", "dtype": "float32", "shape": [], "data": [1.0], "dims": []}, {"name": "obs_z6", "dtype": "float8e4m3fn", "shape": [], "data": [0], "dims": []}], "outputs": ["t7"]}""")
EXPECTED = json.loads(r"""{"outputs": [{"name": "t7", "dtype": "float32", "shape": [1, 1, 1, 1], "want": [NaN], "slack": [0.0]}]}""")
FAILING_LEVELS = ['all', 'disable', 'extended']
CLS = "nan-inf"

DT = {"float32": (TensorProto.FLOAT, np.float32), "uint8": (TensorProto.UINT8, np.uint8),
      "int8": (TensorProto.INT8, np.int8), "uint16": (TensorProto.UINT16, np.uint16),
      "int16": (TensorProto.INT16, np.int16), "int32": (TensorProto.INT32, np.int32),
      "int4": (TensorProto.INT4, np.int8), "uint4": (TensorProto.UINT4, np.uint8),
      "float8e4m3fn": (TensorProto.FLOAT8E4M3FN, np.uint8), "float8e5m2": (TensorProto.FLOAT8E5M2, np.uint8)}
LEVELS = {"disable": ort.GraphOptimizationLevel.ORT_DISABLE_ALL,
          "extended": ort.GraphOptimizationLevel.ORT_ENABLE_EXTENDED,
          "all": ort.GraphOptimizationLevel.ORT_ENABLE_ALL}


def arr(t):
    return np.array(t["data"], dtype=np.float64 if t["dtype"] == "float32" else np.int64) \
        .reshape(t["shape"]).astype(DT[t["dtype"]][1])


def tensor_proto(t):
    elem, _ = DT[t["dtype"]]
    a = arr(t)
    if t["dtype"].startswith("float8"):
        return helper.make_tensor(t["name"], elem, list(a.shape), a.tobytes(), raw=True)
    if t["dtype"] in ("int4", "uint4"):
        return helper.make_tensor(t["name"], elem, list(a.shape), [int(v) for v in a.ravel()])
    return numpy_helper.from_array(a, t["name"])


def build_model():
    nodes = [helper.make_node(n["op"], n["inputs"], n["outputs"], domain=n["domain"] or None, **n["attrs"])
             for n in CASE["nodes"]]
    ins = [helper.make_tensor_value_info(t["name"], DT[t["dtype"]][0], t["shape"]) for t in CASE["inputs"]]
    outs = [helper.make_tensor_value_info(o["name"], DT[o["dtype"]][0], o["shape"]) for o in EXPECTED["outputs"]]
    g = helper.make_graph(nodes, "repro", ins, outs, initializer=[tensor_proto(t) for t in CASE["inits"]])
    opsets = [helper.make_opsetid("", CASE["opset"])]
    if any(n["domain"] == "com.microsoft" for n in CASE["nodes"]):
        opsets.append(helper.make_opsetid("com.microsoft", 1))
    m = helper.make_model(g, opset_imports=opsets)
    m.ir_version = 10
    return m


def run(model, level):
    so = ort.SessionOptions()
    so.graph_optimization_level = LEVELS[level]
    so.intra_op_num_threads = 1
    try:
        s = ort.InferenceSession(model.SerializeToString(), so, providers=["CPUExecutionProvider"])
        feeds = {t["name"]: arr(t) for t in CASE["inputs"]}
        return s.run([o["name"] for o in EXPECTED["outputs"]], feeds), None
    except Exception as e:  # noqa: BLE001
        return None, str(e).splitlines()[0][:300]


def violations(got, o):
    want = np.array(o["want"], dtype=np.float64).reshape(o["shape"])
    slack = np.array(o["slack"], dtype=np.float64).reshape(o["shape"])
    g = np.asarray(got).astype(np.float64)
    both_nan = np.isnan(g) & np.isnan(want)
    same_inf = np.isinf(g) & np.isinf(want) & (np.sign(g) == np.sign(want))
    with np.errstate(invalid="ignore"):
        diff = np.where(both_nan | same_inf, 0.0, np.abs(g - want))
    bad = ~(diff <= slack) & ~np.isinf(slack)
    return [dict(index=[int(i) for i in idx], got=float(g[idx]), want=float(want[idx]), slack=float(slack[idx]))
            for idx in zip(*np.nonzero(bad))]


def main():
    onnx.checker.check_model(build_model(), full_check=True)
    model = build_model()
    report = {"onnxruntime": ort.__version__, "levels": {}}
    reproduced = False
    for level in LEVELS:
        outs, err = run(model, level)
        if err is not None:
            report["levels"][level] = {"error": err}
            if CLS in ("rejects-valid-model", "error-level-dependent") and level in FAILING_LEVELS:
                reproduced = True
            continue
        bad = []
        for got, o in zip(outs, EXPECTED["outputs"]):
            bad += violations(got, o)
        report["levels"][level] = {"n_violations": len(bad), "first": bad[:3]}
        if bad and level in FAILING_LEVELS:
            reproduced = True
    report["reproduced"] = reproduced
    print(json.dumps(report))
    if "--check" in sys.argv and reproduced:
        sys.exit(1)


if __name__ == "__main__":
    main()
